//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ProjectManagerDBEntities2 : DbContext
    {
        public ProjectManagerDBEntities2()
            : base("name=ProjectManagerDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<getDefaultProject_Result> getDefaultProject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDefaultProject_Result>("getDefaultProject");
        }
    }
}
