//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    using Model;
    
    public partial class ProjectManagerDBEntities : DbContext
    {
        public ProjectManagerDBEntities()
            : base("name=ProjectManagerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<userinfo> userinfo { get; set; }
    
        public virtual ObjectResult<Check_Login_Result> Check_Login(string adminUser, string adminPwd)
        {
            var adminUserParameter = adminUser != null ?
                new ObjectParameter("adminUser", adminUser) :
                new ObjectParameter("adminUser", typeof(string));
    
            var adminPwdParameter = adminPwd != null ?
                new ObjectParameter("adminPwd", adminPwd) :
                new ObjectParameter("adminPwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Check_Login_Result>("Check_Login", adminUserParameter, adminPwdParameter);
        }
    }
}
